<?php
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
include_once $GLOBALS['THRIFT_ROOT'].'/Thrift.php';

include_once $GLOBALS['THRIFT_ROOT'].'/packages/wtcommon/wtcommon_types.php';
include_once $GLOBALS['THRIFT_ROOT'].'/packages/xcache_shared/xcache_shared_types.php';

?>
