<?php
return array (
    1=>array(
          'Id'=>1,
          'LevelRequire'=>1,
          'Name'=>'Cá hóa thạch',
          'TimeUse'=>'',
          'Money'=>1,
          'ZMoney'=>'',
          'Version'=>'v1',
     ),
    2=>array(
          'Id'=>2,
          'LevelRequire'=>3,
          'Name'=>'Bóng biển',
          'TimeUse'=>'',
          'Money'=>8,
          'ZMoney'=>'',
          'Version'=>'v1',
     ),
    3=>array(
          'Id'=>3,
          'LevelRequire'=>5,
          'Name'=>'Đuôi cá',
          'TimeUse'=>'',
          'Money'=>10,
          'ZMoney'=>'',
          'Version'=>'v1',
     ),
    4=>array(
          'Id'=>4,
          'LevelRequire'=>9,
          'Name'=>'Trứng cá',
          'TimeUse'=>'',
          'Money'=>20,
          'ZMoney'=>'',
          'Version'=>'v1',
     ),
    5=>array(
          'Id'=>5,
          'LevelRequire'=>15,
          'Name'=>'Vỏ Ốc',
          'TimeUse'=>'',
          'Money'=>32,
          'ZMoney'=>'',
          'Version'=>'v1',
     ),
    6=>array(
          'Id'=>6,
          'LevelRequire'=>19,
          'Name'=>'Ván trượt',
          'TimeUse'=>'',
          'Money'=>40,
          'ZMoney'=>'',
          'Version'=>'v1',
     ),
    7=>array(
          'Id'=>7,
          'LevelRequire'=>22,
          'Name'=>'Kính lặn',
          'TimeUse'=>'',
          'Money'=>54,
          'ZMoney'=>'',
          'Version'=>'v1',
     ),
    8=>array(
          'Id'=>8,
          'LevelRequire'=>24,
          'Name'=>'Bình hơi',
          'TimeUse'=>'',
          'Money'=>64,
          'ZMoney'=>'',
          'Version'=>'v1',
     ),
    9=>array(
          'Id'=>9,
          'LevelRequire'=>26,
          'Name'=>'SuShi',
          'TimeUse'=>'',
          'Money'=>68,
          'ZMoney'=>'',
          'Version'=>'v1',
     ),
    10=>array(
          'Id'=>10,
          'LevelRequire'=>32,
          'Name'=>'Tôm đông lạnh',
          'TimeUse'=>'',
          'Money'=>70,
          'ZMoney'=>'',
          'Version'=>'v1',
     ),
    11=>array(
          'Id'=>11,
          'LevelRequire'=>36,
          'Name'=>'Vịt Phao',
          'TimeUse'=>'',
          'Money'=>74,
          'ZMoney'=>'',
          'Version'=>'v1',
     ),
);
?>