<?php
return array (
     1=>array(
         'Id'=>1,
         'LevelRequire'=>1,
         'Money'=>'',
         'ZMoney'=>'',
         'Exp'=>'',
),
     2=>array(
         'Id'=>2,
         'LevelRequire'=>1,
         'Money'=>'',
         'ZMoney'=>'',
         'Exp'=>'',
),
     3=>array(
         'Id'=>3,
         'LevelRequire'=>1,
         'Money'=>'',
         'ZMoney'=>'',
         'Exp'=>'',
),
     4=>array(
         'Id'=>4,
         'LevelRequire'=>13,
         'Money'=>20000,
         'ZMoney'=>10,
         'Exp'=>40,
),
     5=>array(
         'Id'=>5,
         'LevelRequire'=>16,
         'Money'=>50000,
         'ZMoney'=>30,
         'Exp'=>120,
),
     6=>array(
         'Id'=>6,
         'LevelRequire'=>19,
         'Money'=>100000,
         'ZMoney'=>65,
         'Exp'=>260,
),
     7=>array(
         'Id'=>7,
         'LevelRequire'=>22,
         'Money'=>'',
         'ZMoney'=>'',
         'Exp'=>'',
),
     8=>array(
         'Id'=>8,
         'LevelRequire'=>25,
         'Money'=>'',
         'ZMoney'=>'',
         'Exp'=>'',
),
     9=>array(
         'Id'=>9,
         'LevelRequire'=>40,
         'Money'=>'',
         'ZMoney'=>'',
         'Exp'=>'',
),
)
?>