<?php
return array (
     1=>array(
         'Name'=>'C mi',
         'Id'=>1,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>60,
         'OverLevel2'=>40,
     ),
     2=>array(
         'Name'=>'Cá củ cải',
         'Id'=>2,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>60,
         'OverLevel2'=>40,
     ),
     3=>array(
         'Name'=>'C carot',
         'Id'=>3,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>60,
         'OverLevel2'=>40,
     ),
     4=>array(
         'Name'=>'Cá vẹt lùn',
         'Id'=>4,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>60,
         'OverLevel2'=>40,
     ),
     5=>array(
         'Name'=>'Cá Thủy Tinh',
         'Id'=>5,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>60,
         'OverLevel2'=>40,
     ),
     6=>array(
         'Name'=>'Cá hề Cory',
         'Id'=>6,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>60,
         'OverLevel2'=>40,
     ),
     7=>array(
         'Name'=>'Cá lưỡi liềm',
         'Id'=>7,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>60,
         'OverLevel2'=>40,
     ),
     8=>array(
         'Name'=>'C Nobita',
         'Id'=>8,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>60,
         'OverLevel2'=>40,
     ),
     9=>array(
         'Name'=>'Thia lia mắt trố',
         'Id'=>9,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>60,
         'OverLevel2'=>40,
     ),
     10=>array(
         'Name'=>'Cá mỏ nhọn',
         'Id'=>10,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>60,
         'OverLevel2'=>40,
     ),
     11=>array(
         'Name'=>'Cá Cẩm Thạch',
         'Id'=>11,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>60,
         'OverLevel2'=>40,
     ),
     12=>array(
         'Name'=>'Cá đĩa',
         'Id'=>12,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>60,
         'OverLevel2'=>40,
     ),
     13=>array(
         'Name'=>'Cá Thủ Lù',
         'Id'=>13,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>60,
         'OverLevel2'=>40,
     ),
     14=>array(
         'Name'=>'C Cu Li',
         'Id'=>14,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>60,
         'OverLevel2'=>40,
     ),
     15=>array(
         'Name'=>'C Bong Bng',
         'Id'=>15,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>60,
         'OverLevel2'=>40,
     ),
     16=>array(
         'Name'=>'Nemo Bo ',
         'Id'=>16,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>70,
         'OverLevel2'=>30,
     ),
     17=>array(
         'Name'=>'Cá Chuột',
         'Id'=>17,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>70,
         'OverLevel2'=>30,
     ),
     18=>array(
         'Name'=>'C Mm',
         'Id'=>18,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>70,
         'OverLevel2'=>30,
     ),
     19=>array(
         'Name'=>'Cá Xương Rồng',
         'Id'=>19,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>70,
         'OverLevel2'=>30,
     ),
     20=>array(
         'Name'=>'C cau c',
         'Id'=>20,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>70,
         'OverLevel2'=>30,
     ),
     21=>array(
         'Name'=>'C Cng Cha',
         'Id'=>21,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>70,
         'OverLevel2'=>30,
     ),
     22=>array(
         'Name'=>'C La St',
         'Id'=>22,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>70,
         'OverLevel2'=>30,
     ),
     23=>array(
         'Name'=>'Cá đèn Xu Xu',
         'Id'=>23,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>70,
         'OverLevel2'=>30,
     ),
     24=>array(
         'Name'=>'Cá sư tử',
         'Id'=>24,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>70,
         'OverLevel2'=>30,
     ),
     25=>array(
         'Name'=>'C Chanh',
         'Id'=>25,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>70,
         'OverLevel2'=>30,
     ),
     26=>array(
         'Name'=>'cá nóc sừng',
         'Id'=>26,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>80,
         'OverLevel2'=>20,
     ),
     27=>array(
         'Name'=>'C Picaso',
         'Id'=>27,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>80,
         'OverLevel2'=>20,
     ),
     28=>array(
         'Name'=>'Cá chép nhật',
         'Id'=>28,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>80,
         'OverLevel2'=>20,
     ),
     29=>array(
         'Name'=>'Cá Hồ Điệp',
         'Id'=>29,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>80,
         'OverLevel2'=>20,
     ),
     30=>array(
         'Name'=>'Cá Bống Cát',
         'Id'=>30,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>80,
         'OverLevel2'=>20,
     ),
     31=>array(
         'Name'=>'Cá mập hải tặc',
         'Id'=>31,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>80,
         'OverLevel2'=>20,
     ),
     32=>array(
         'Name'=>'Cá một sừng',
         'Id'=>32,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>80,
         'OverLevel2'=>20,
     ),
     33=>array(
         'Name'=>'C heo Molly',
         'Id'=>33,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>80,
         'OverLevel2'=>20,
     ),
     34=>array(
         'Name'=>'Cá ngựa đầu đinh',
         'Id'=>34,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>80,
         'OverLevel2'=>20,
     ),
     35=>array(
         'Name'=>'Cá thỏ',
         'Id'=>35,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>80,
         'OverLevel2'=>20,
     ),
     36=>array(
         'Name'=>'C co',
         'Id'=>36,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     37=>array(
         'Name'=>'Chép giấy',
         'Id'=>37,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     38=>array(
         'Name'=>'rồng nhí',
         'Id'=>38,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     39=>array(
         'Name'=>'Cá voi hoàng đế',
         'Id'=>39,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     40=>array(
         'Name'=>'Cá mặt trời',
         'Id'=>40,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     41=>array(
         'Name'=>'Rapper',
         'Id'=>41,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     42=>array(
         'Name'=>'Quỷ đỏ',
         'Id'=>42,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     43=>array(
         'Name'=>'Mặt nạ',
         'Id'=>43,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     44=>array(
         'Name'=>'C 51',
         'Id'=>44,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     45=>array(
         'Name'=>'C 51 + 1',
         'Id'=>45,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     46=>array(
         'Name'=>'C 51 + 2',
         'Id'=>46,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     47=>array(
         'Name'=>'C 51 + 3',
         'Id'=>47,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     48=>array(
         'Name'=>'C 51 + 4',
         'Id'=>48,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     49=>array(
         'Name'=>'C 51 + 5',
         'Id'=>49,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     50=>array(
         'Name'=>'C 57',
         'Id'=>50,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     51=>array(
         'Name'=>'C 57 + 1',
         'Id'=>51,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     52=>array(
         'Name'=>'C 57 + 2',
         'Id'=>52,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     53=>array(
         'Name'=>'C 57 + 3',
         'Id'=>53,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     54=>array(
         'Name'=>'C 57 + 4',
         'Id'=>54,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     55=>array(
         'Name'=>'C 57 + 5',
         'Id'=>55,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     56=>array(
         'Name'=>'C 63',
         'Id'=>56,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     57=>array(
         'Name'=>'C 63 + 1',
         'Id'=>57,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     58=>array(
         'Name'=>'C 63 + 2',
         'Id'=>58,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     59=>array(
         'Name'=>'C 63 + 3',
         'Id'=>59,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     60=>array(
         'Name'=>'C 63 + 4',
         'Id'=>60,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     61=>array(
         'Name'=>'C 63 + 5',
         'Id'=>61,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     62=>array(
         'Name'=>'C 69',
         'Id'=>62,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     63=>array(
         'Name'=>'C 69 + 1',
         'Id'=>63,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     64=>array(
         'Name'=>'C 69 + 2',
         'Id'=>64,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     65=>array(
         'Name'=>'C 69 + 3',
         'Id'=>65,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     66=>array(
         'Name'=>'C 69 + 4',
         'Id'=>66,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     67=>array(
         'Name'=>'C 69 + 5',
         'Id'=>67,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     68=>array(
         'Name'=>'C 75',
         'Id'=>68,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     69=>array(
         'Name'=>'C 75 + 1',
         'Id'=>69,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     70=>array(
         'Name'=>'C 75 + 2',
         'Id'=>70,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     71=>array(
         'Name'=>'C 75 + 3',
         'Id'=>71,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     72=>array(
         'Name'=>'C 75 + 4',
         'Id'=>72,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     73=>array(
         'Name'=>'C 75 + 5',
         'Id'=>73,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     74=>array(
         'Name'=>'C 81',
         'Id'=>74,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     75=>array(
         'Name'=>'C 81 + 1',
         'Id'=>75,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     76=>array(
         'Name'=>'C 81 + 2',
         'Id'=>76,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     77=>array(
         'Name'=>'C 81 + 3',
         'Id'=>77,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     78=>array(
         'Name'=>'C 81 + 4',
         'Id'=>78,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     79=>array(
         'Name'=>'C 81 + 5',
         'Id'=>79,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     80=>array(
         'Name'=>'C 87',
         'Id'=>80,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     81=>array(
         'Name'=>'C 87 + 1',
         'Id'=>81,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     82=>array(
         'Name'=>'C 87 + 2',
         'Id'=>82,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     83=>array(
         'Name'=>'C 87 + 3',
         'Id'=>83,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     84=>array(
         'Name'=>'C 87 + 4',
         'Id'=>84,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     85=>array(
         'Name'=>'C 87 + 5',
         'Id'=>85,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     86=>array(
         'Name'=>'C 88',
         'Id'=>86,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     87=>array(
         'Name'=>'C 88 + 1',
         'Id'=>87,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     88=>array(
         'Name'=>'C 88 + 2',
         'Id'=>88,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     89=>array(
         'Name'=>'C 88 + 3',
         'Id'=>89,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     90=>array(
         'Name'=>'C 88 + 4',
         'Id'=>90,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     91=>array(
         'Name'=>'C 88 + 5',
         'Id'=>91,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     92=>array(
         'Name'=>'C89',
         'Id'=>92,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
     93=>array(
         'Name'=>'C 89 + 1',
         'Id'=>93,
         'RateOverMix'=>10,
         'MaxOverLevel'=>100,
         'OverLevel1'=>90,
         'OverLevel2'=>10,
     ),
)
?>