<?php return array (
  1 => 
  array (
    'PointRequire' => 50,
    'TurnDefend' => 0,
    'MaxHealth' => 10,
    'AttackPoint' => 1,
    'AttackEnergy' => 3,
    'RegenTime' => 300,
    'Critical' => 0.2,
    'Vitality' => 400,
    'Rate' => 1,
    'RateDamage' => 0,
    'RateDefence' => 0,
    'RateVitality' => 0,
    'RateCritical' => 0,
    'Gem' => array(0 => array('GemId'=>0,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>1,'Num'=>3,'Rate'=>1)),
  ),
  2 => 
  array (
    'PointRequire' => 300,
    'TurnDefend' => 0,
    'MaxHealth' => 15,
    'AttackPoint' => 1,
    'AttackEnergy' => 3,
    'RegenTime' => 300,
    'Critical' => 0.3,
    'Vitality' => 500,
    'Rate' => 1.3,
    'RateDamage' => 0.2,
    'RateDefence' => 0.2,
    'RateVitality' => 0.2,
    'RateCritical' => 0.2,
    'Gem' => array(0 => array('GemId'=>0,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>1,'Num'=>3,'Rate'=>1)),
  ),
  3 => 
  array (
    'PointRequire' => 1000,
    'TurnDefend' => 30,
    'MaxHealth' => 20,
    'AttackPoint' => 1,
    'AttackEnergy' => 5,
    'RegenTime' => 240,
    'Critical' => 0.5,
    'Vitality' => 600,
    'Rate' => 1.7,
    'RateDamage' => 0.2,
    'RateDefence' => 0.2,
    'RateVitality' => 0.2,
    'RateCritical' => 0.2,
    'Gem' => array(0 => array('GemId'=>0,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>1,'Num'=>3,'Rate'=>1)),
  ),
  4 => 
  array (
    'PointRequire' => 5000,
    'TurnDefend' => 40,
    'MaxHealth' => 50,
    'AttackPoint' => 2,
    'AttackEnergy' => 5,
    'RegenTime' => 180,
    'Critical' => 1,
    'Vitality' => 700,
    'Rate' => 2,
    'RateDamage' => 0.2,
    'RateDefence' => 0.2,
    'RateVitality' => 0.2,
    'RateCritical' => 0.2,
    'Gem' => array(0 => array('GemId'=>1,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>2,'Num'=>3,'Rate'=>1)),
  ),
  5 => 
  array (
    'PointRequire' => 10000,
    'TurnDefend' => 50,
    'MaxHealth' => 80,
    'AttackPoint' => 3,
    'AttackEnergy' => 7,
    'RegenTime' => 120,
    'Critical' => 1.5,
    'Vitality' => 800,
    'Rate' => 2.3,
    'RateDamage' => 0.2,
    'RateDefence' => 0.2,
    'RateVitality' => 0.2,
    'RateCritical' => 0.2,
    'Gem' => array(0 => array('GemId'=>1,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>2,'Num'=>3,'Rate'=>1)), 
  ),
  6 => 
  array (
    'PointRequire' => 20000,
    'TurnDefend' => 60,
    'MaxHealth' => 120,
    'AttackPoint' => 4,
    'AttackEnergy' => 7,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.2,
    'RateDefence' => 0.2,
    'RateVitality' => 0.2,
    'RateCritical' => 0.2,
    'Gem' => array(0 => array('GemId'=>1,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>2,'Num'=>3,'Rate'=>1)), 
  ),
  7 => 
  array (
    'PointRequire' => 40000,
    'TurnDefend' => 70,
    'MaxHealth' => 175,
    'AttackPoint' => 5,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'RateDamage' => 0.2,
    'RateDefence' => 0.2,
    'RateVitality' => 0.2,
    'RateCritical' => 0.2,
  	'Gem' => array(0 => array('GemId'=>1,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>2,'Num'=>3,'Rate'=>1)), 
  ),
  8 => 
  array (
    'PointRequire' => 80000,
    'TurnDefend' => 80,
    'MaxHealth' => 240,
    'AttackPoint' => 6,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'RateDamage' => 0.2,
    'RateDefence' => 0.2,
    'RateVitality' => 0.2,
    'RateCritical' => 0.2,
 	'Gem' => array(0 => array('GemId'=>1,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>2,'Num'=>3,'Rate'=>1)), 
  ),
  9 => 
  array (
    'PointRequire' => 160000,
    'TurnDefend' => 90,
    'MaxHealth' => 315,
    'AttackPoint' => 7,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'RateDamage' => 0.2,
    'RateDefence' => 0.2,
    'RateVitality' => 0.2,
    'RateCritical' => 0.2,
  	'Gem' => array(0 => array('GemId'=>1,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>2,'Num'=>3,'Rate'=>1)), 
  ),
  10 => 
  array (
    'PointRequire' => 320000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'RateDamage' => 0.2,
    'RateDefence' => 0.2,
    'RateVitality' => 0.2,
    'RateCritical' => 0.2,
  	'Gem' => array(0 => array('GemId'=>1,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>2,'Num'=>3,'Rate'=>1)), 
  ),
  11 => 
  array (
    'PointRequire' => 640000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'RateDamage' => 0.2,
    'RateDefence' => 0.2,
    'RateVitality' => 0.2,
    'RateCritical' => 0.2,
	'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)), 
  ),
  12 => 
  array (
    'PointRequire' => 1280000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'RateDamage' => 0.2,
    'RateDefence' => 0.2,
    'RateVitality' => 0.2,
    'RateCritical' => 0.2,
	'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)), 
  ),
  13 => 
  array (
    'PointRequire' => 1280000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'RateDamage' => 0.2,
    'RateDefence' => 0.2,
    'RateVitality' => 0.2,
    'RateCritical' => 0.2,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)), 
  ),
  14 => 
  array (
    'PointRequire' => 1280000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'RateDamage' => 0.2,
    'RateDefence' => 0.2,
    'RateVitality' => 0.2,
    'RateCritical' => 0.2,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)), 
  ),
  15 => 
  array (
    'PointRequire' => 1280000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'RateDamage' => 0.2,
    'RateDefence' => 0.2,
    'RateVitality' => 0.2,
    'RateCritical' => 0.2,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)), 
  ),
  16 => 
  array (
    'PointRequire' => 1280000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'RateDamage' => 0.2,
    'RateDefence' => 0.2,
    'RateVitality' => 0.2,
    'RateCritical' => 0.2,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)), 
  ),
  17 => 
  array (
    'PointRequire' => 1280000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'RateDamage' => 0.2,
    'RateDefence' => 0.2,
    'RateVitality' => 0.2,
    'RateCritical' => 0.2,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)), 
  ),
  18 => 
  array (
    'PointRequire' => 1280000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'RateDamage' => 0.2,
    'RateDefence' => 0.2,
    'RateVitality' => 0.2,
    'RateCritical' => 0.2,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)), 
  ),
  19 => 
  array (
    'PointRequire' => 1280000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'RateDamage' => 0.2,
    'RateDefence' => 0.2,
    'RateVitality' => 0.2,
    'RateCritical' => 0.2,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)), 
  ),
  20 => 
  array (
    'Name' => '??u Chi?n Th?ng Ph?t',
    'PointRequire' => 1280000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.19,
    'RateDefence' => 0.19,
    'RateVitality' => 0.19,
    'RateCritical' => 0.19,
 	'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)), 
  ),
  21 => 
  array (
    'Name' => 'Anh H?ng H?o Ki?t',
    'PointRequire' => 1480000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.18,
    'RateDefence' => 0.18,
    'RateVitality' => 0.18,
    'RateCritical' => 0.18,
 	'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)), 
  ),
  22 => 
  array (
    'Name' => 'T? ??i Giai Kh?ng',
    'PointRequire' => 1680000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.17,
    'RateDefence' => 0.17,
    'RateVitality' => 0.17,
    'RateCritical' => 0.17,
 	'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)), 
  ),
  23 => 
  array (
    'Name' => 'Tung Ho?nh Thi?n H?',
    'PointRequire' => 1880000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.16,
    'RateDefence' => 0.16,
    'RateVitality' => 0.16,
    'RateCritical' => 0.16,
 	'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)), 
  ),
  24 => 
  array (
    'Name' => '??i Khai S?t Gi?i',
    'PointRequire' => 2080000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.15,
    'RateDefence' => 0.15,
    'RateVitality' => 0.15,
    'RateCritical' => 0.15,
 	'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)), 
  ),
  25 => 
  array (
    'Name' => 'B? ??o V? L?m',
    'PointRequire' => 2280000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.145,
    'RateDefence' => 0.145,
    'RateVitality' => 0.145,
    'RateCritical' => 0.145,
 	'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)), 
  ),
  26 => 
  array (
    'Name' => 'Qu? Kh?c Th?n S?u',
    'PointRequire' => 2480000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.14,
    'RateDefence' => 0.14,
    'RateVitality' => 0.14,
    'RateCritical' => 0.14,
 	'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)), 
  ),
  27 => 
  array (
    'Name' => 'Kim Cang Th?n Ng?',
    'PointRequire' => 2680000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.135,
    'RateDefence' => 0.135,
    'RateVitality' => 0.135,
    'RateCritical' => 0.135,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)), 
  ),
  28 => 
  array (
    'Name' => 'Th?u Thi?n Ho?n Nh?t',
    'PointRequire' => 2880000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.13,
    'RateDefence' => 0.13,
    'RateVitality' => 0.13,
    'RateCritical' => 0.13,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)), 
  ),
  29 => 
  array (
    'Name' => 'Ch?n M?nh Thi?n T?',
    'PointRequire' => 3080000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.125,
    'RateDefence' => 0.125,
    'RateVitality' => 0.125,
    'RateCritical' => 0.125,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)), 
  ),
  30 => 
  array (
    'Name' => 'Xu?t Qu? Nh?p Th?n',
    'PointRequire' => 3480000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.1225,
    'RateDefence' => 0.1225,
    'RateVitality' => 0.1225,
    'RateCritical' => 0.1225,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),  
  ),
  31 => 
  array (
    'Name' => 'M?nh Long Qu? Giang',
    'PointRequire' => 3880000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.12,
    'RateDefence' => 0.12,
    'RateVitality' => 0.12,
    'RateCritical' => 0.12,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),  
  ),
  32 => 
  array (
    'Name' => 'Th?n ?i?u ??i Hi?p',
    'PointRequire' => 4280000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.1175,
    'RateDefence' => 0.1175,
    'RateVitality' => 0.1175,
    'RateCritical' => 0.1175,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),  
  ),
  33 => 
  array (
    'Name' => 'Cu?ng Phong L?o B?',
    'PointRequire' => 4680000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.115,
    'RateDefence' => 0.115,
    'RateVitality' => 0.115,
    'RateCritical' => 0.115,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),  
  ),
  34 => 
  array (
    'Name' => 'Xoay Chuy?n C?n Kh?n',
    'PointRequire' => 5080000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.1125,
    'RateDefence' => 0.1125,
    'RateVitality' => 0.1125,
    'RateCritical' => 0.1125,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),  
  ),
  35 => 
  array (
    'Name' => 'H?ng Long Ph?c Ma',
    'PointRequire' => 5480000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),  
  ),
  36 => 
  array (
    'Name' => 'Th?ng L?nh Thi?n H?',
    'PointRequire' => 5880000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),  
  ),
  37 => 
  array (
    'Name' => 'Th?n Quy?n V? ??ch',
    'PointRequire' => 6280000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),  
  ),
  38 => 
  array (
    'Name' => 'V? L?m C?u ??nh',
    'PointRequire' => 6680000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),  
  ),
  39 => 
  array (
    'Name' => 'V? ??ch Thi?n H?',
    'PointRequire' => 7080000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),  
  ),
  40 => 
  array (
    'Name' => 'Huy?n Tho?i Ng? Chi?n',
    'PointRequire' => 7480000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),  
  ),
  41 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 7880000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  42 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 8280000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  43 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 8680000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  44 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 9080000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  45 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 9480000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  46 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 9880000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  47 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 10280000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  48 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 10680000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  49 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 11080000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  50 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 11480000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  51 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 11880000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  52 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 12280000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  53 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 12680000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  54 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 13080000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  55 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 13480000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  56 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 13880000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  57 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 14280000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  58 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 14680000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  59 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 15080000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  60 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 15480000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  61 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 15880000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  62 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 16280000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  63 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 16680000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  64 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 17080000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  65 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 17480000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  66 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 17880000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  67 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 18280000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  68 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 18680000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  69 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 19080000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
  70 => 
  array (
    'Name' => 'Thần Ngư',
    'PointRequire' => 19480000,
    'TurnDefend' => 100,
    'MaxHealth' => 400,
    'AttackPoint' => 8,
    'AttackEnergy' => 9,
    'RegenTime' => 60,
    'Critical' => 2,
    'Vitality' => 900,
    'Rate' => 2.7,
    'RateDamage' => 0.11,
    'RateDefence' => 0.11,
    'RateVitality' => 0.11,
    'RateCritical' => 0.11,
    'Gem' => array(0 => array('GemId'=>2,'Num'=>3,'Rate'=>99), 1 => array('GemId'=>3,'Num'=>3,'Rate'=>1)),      
  ),
);