<?php
return array (
  0 => array(
             'Rate' => array(1=>10,2=>10),
             'Level' => array(1,10),
              1 => array(OptionFish::MONEY => rand(1,4)),
              2 => array(OptionFish::EXP => rand(1,4)),
            ),
  1 => array(
             'Rate' => array(1=>10,2=>10),
             'Level' => array(11,20),
              1 => array(OptionFish::MONEY => rand(3,7)),
              2 => array(OptionFish::EXP => rand(3,7)),
            ),
  2 => array(
             'Rate' => array(1=>10,2=>10),
             'Level' => array(21,30),
              1 => array(OptionFish::MONEY => rand(5,10)),
              2 => array(OptionFish::EXP => rand(5,10)),
            ),
  3 => array(
             'Rate' => array(1=>30,2=>30,3=>30),
             'Level' => array(31,40),
              1 => array(OptionFish::MONEY => rand(7,13)),
              2 => array(OptionFish::EXP => rand(7,13)),
              3 => array(OptionFish::EXP => rand(5,9),
                         OptionFish::MONEY => rand(5,9),
                        ),
            ),
  4 => array(
             'Rate' => array(1=>30,2=>30,3=>30,4=>10),
             'Level' => array(41,50),
              1 => array(OptionFish::MONEY => rand(9,16)),
              2 => array(OptionFish::EXP => rand(9,16)),
              3 => array(OptionFish::EXP => rand(8,12),
                         OptionFish::MONEY => rand(8,12),
                        ),
              4 => array(OptionFish::EXP => rand(7,10),
                         OptionFish::MONEY => rand(7,10),
                         OptionFish::TIME => rand(7,10),
                        ),
            ),
  5 => array(
             'Rate' => array(1=>30,2=>30,3=>30,4=>10),
             'Level' => array(51,60),
              1 => array(OptionFish::MONEY => rand(10,17)),
              2 => array(OptionFish::EXP => rand(10,17)),
              3 => array(OptionFish::EXP => rand(9,13),
                         OptionFish::MONEY => rand(9,13),
                        ),
              4 => array(OptionFish::EXP => rand(8,11),
                         OptionFish::MONEY => rand(8,11),
                         OptionFish::TIME => rand(8,11),
                        ),
            ),
  6 => array(
             'Rate' => array(1=>30,2=>30,3=>30,4=>10),
             'Level' => array(61,70),
              1 => array(OptionFish::MONEY => rand(11,18)),
              2 => array(OptionFish::EXP => rand(11,18)),
              3 => array(OptionFish::EXP => rand(10,14),
                         OptionFish::MONEY => rand(10,14),
                        ),
              4 => array(OptionFish::EXP => rand(9,12),
                         OptionFish::MONEY => rand(9,12),
                         OptionFish::TIME => rand(9,12),
                        ),
            ),
  7 => array(
             'Rate' => array(1=>30,2=>30,3=>30,4=>10),
             'Level' => array(71,80),
              1 => array(OptionFish::MONEY => rand(12,19)),
              2 => array(OptionFish::EXP => rand(12,19)),
              3 => array(OptionFish::EXP => rand(11,15),
                         OptionFish::MONEY => rand(11,15),
                        ),
              4 => array(OptionFish::EXP => rand(10,13),
                         OptionFish::MONEY => rand(10,13),
                         OptionFish::TIME => rand(10,13),
                        ),
            ),
  8 => array(
             'Rate' => array(1=>30,2=>30,3=>30,4=>10),
             'Level' => array(81,90),
              1 => array(OptionFish::MONEY => rand(13,20)),
              2 => array(OptionFish::EXP => rand(13,20)),
              3 => array(OptionFish::EXP => rand(12,16),
                         OptionFish::MONEY => rand(12,16),
                        ),
              4 => array(OptionFish::EXP => rand(11,14),
                         OptionFish::MONEY => rand(11,14),
                         OptionFish::TIME => rand(11,14),
                        ),
            ),
  9 => array(
             'Rate' => array(1=>30,2=>30,3=>30,4=>10),
             'Level' => array(91,100),
              1 => array(OptionFish::MONEY => rand(14,21)),
              2 => array(OptionFish::EXP => rand(14,21)),
              3 => array(OptionFish::EXP => rand(13,17),
                         OptionFish::MONEY => rand(13,17),
                        ),
              4 => array(OptionFish::EXP => rand(12,15),
                         OptionFish::MONEY => rand(13,17),
                         OptionFish::TIME => rand(13,17),
                        ),
            ),
);
?>
    