<?php return array (
  'QWhite' => 
  array (
    1 => 
    array (
      'Name' => 'Huy Hieu Dung Cam',
      'OptionDamage' => 1,
      'Damage' => 10,
      'OptionDefence' => 1,
      'Defence' => 10,
      'OptionCritical' => 1,
      'Critical' => 3,
      'OptionVitality' => 1,
      'Vitality' => 30,
      'Rate' => 15,
      'Star' => 1,
    ),
    2 => 
    array (
      'Name' => 'Huy Hieu Kien Cuong',
      'OptionDamage' => 1,
      'Damage' => 15,
      'OptionDefence' => 1,
      'Defence' => 15,
      'OptionCritical' => 1,
      'Critical' => 5,
      'OptionVitality' => 1,
      'Vitality' => 45,
      'Rate' => 15,
      'Star' => 1,
    ),
    3 => 
    array (
      'Name' => 'Huy Hieu Suc Manh',
      'OptionDamage' => 1,
      'Damage' => 20,
      'OptionDefence' => 1,
      'Defence' => 20,
      'OptionCritical' => 1,
      'Critical' => 6,
      'OptionVitality' => 1,
      'Vitality' => 60,
      'Rate' => 15,
      'Star' => 1,
    ),
    4 => 
    array (
      'Name' => 'Huy Hieu Khong Tuoc',
      'OptionDamage' => 1,
      'Damage' => 25,
      'OptionDefence' => 1,
      'Defence' => 25,
      'OptionCritical' => 1,
      'Critical' => 8,
      'OptionVitality' => 1,
      'Vitality' => 75,
      'Rate' => 15,
      'Star' => 2,
    ),
    5 => 
    array (
      'Name' => 'Huy Hieu Chien Tranh',
      'OptionDamage' => 1,
      'Damage' => 30,
      'OptionDefence' => 1,
      'Defence' => 30,
      'OptionCritical' => 1,
      'Critical' => 10,
      'OptionVitality' => 1,
      'Vitality' => 90,
      'Rate' => 15,
      'Star' => 2,
    ),
    6 => 
    array (
      'Name' => 'Huy Hieu Bao Ve',
      'OptionDamage' => 1,
      'Damage' => 35,
      'OptionDefence' => 1,
      'Defence' => 35,
      'OptionCritical' => 1,
      'Critical' => 11,
      'OptionVitality' => 1,
      'Vitality' => 105,
      'Rate' => 5,
      'Star' => 3,
    ),
    7 => 
    array (
      'Name' => 'Huy Hieu Than Linh',
      'OptionDamage' => 1,
      'Damage' => 40,
      'OptionDefence' => 1,
      'Defence' => 40,
      'OptionCritical' => 1,
      'Critical' => 13,
      'OptionVitality' => 1,
      'Vitality' => 120,
      'Rate' => 5,
      'Star' => 3,
    ),
    8 => 
    array (
      'Name' => 'Huy Hieu Bien Ca',
      'OptionDamage' => 1,
      'Damage' => 45,
      'OptionDefence' => 1,
      'Defence' => 45,
      'OptionCritical' => 1,
      'Critical' => 15,
      'OptionVitality' => 1,
      'Vitality' => 135,
      'Rate' => 5,
      'Star' => 4,
    ),
    9 => 
    array (
      'Name' => 'Huy Hieu Song Ngu',
      'OptionDamage' => 1,
      'Damage' => 50,
      'OptionDefence' => 1,
      'Defence' => 50,
      'OptionCritical' => 1,
      'Critical' => 16,
      'OptionVitality' => 1,
      'Vitality' => 150,
      'Rate' => 5,
      'Star' => 4,
    ),
    10 => 
    array (
      'Name' => 'Huy Hieu Than Ngu',
      'OptionDamage' => 1,
      'Damage' => 55,
      'OptionDefence' => 1,
      'Defence' => 55,
      'OptionCritical' => 1,
      'Critical' => 18,
      'OptionVitality' => 1,
      'Vitality' => 165,
      'Rate' => 5,
      'Star' => 5,
    ),
  ),
  'QGreen' => 
  array (
    1 => 
    array (
      'Name' => 'Huy Hieu Dung Cam',
      'OptionDamage' => 1,
      'Damage' => 100,
      'OptionDefence' => 1,
      'Defence' => 100,
      'OptionCritical' => 1,
      'Critical' => 33,
      'OptionVitality' => 1,
      'Vitality' => 300,
      'Rate' => 15,
      'Star' => 1,
    ),
    2 => 
    array (
      'Name' => 'Huy Hieu Kien Cuong',
      'OptionDamage' => 1,
      'Damage' => 110,
      'OptionDefence' => 1,
      'Defence' => 110,
      'OptionCritical' => 1,
      'Critical' => 36,
      'OptionVitality' => 1,
      'Vitality' => 330,
      'Rate' => 15,
      'Star' => 1,
    ),
    3 => 
    array (
      'Name' => 'Huy Hieu Suc Manh',
      'OptionDamage' => 1,
      'Damage' => 120,
      'OptionDefence' => 1,
      'Defence' => 120,
      'OptionCritical' => 1,
      'Critical' => 40,
      'OptionVitality' => 1,
      'Vitality' => 360,
      'Rate' => 15,
      'Star' => 1,
    ),
    4 => 
    array (
      'Name' => 'Huy Hieu Khong Tuoc',
      'OptionDamage' => 1,
      'Damage' => 130,
      'OptionDefence' => 1,
      'Defence' => 130,
      'OptionCritical' => 1,
      'Critical' => 43,
      'OptionVitality' => 1,
      'Vitality' => 390,
      'Rate' => 15,
      'Star' => 2,
    ),
    5 => 
    array (
      'Name' => 'Huy Hieu Chien Tranh',
      'OptionDamage' => 1,
      'Damage' => 140,
      'OptionDefence' => 1,
      'Defence' => 140,
      'OptionCritical' => 1,
      'Critical' => 46,
      'OptionVitality' => 1,
      'Vitality' => 420,
      'Rate' => 15,
      'Star' => 2,
    ),
    6 => 
    array (
      'Name' => 'Huy Hieu Bao Ve',
      'OptionDamage' => 1,
      'Damage' => 150,
      'OptionDefence' => 1,
      'Defence' => 150,
      'OptionCritical' => 1,
      'Critical' => 50,
      'OptionVitality' => 1,
      'Vitality' => 450,
      'Rate' => 5,
      'Star' => 3,
    ),
    7 => 
    array (
      'Name' => 'Huy Hieu Than Linh',
      'OptionDamage' => 1,
      'Damage' => 160,
      'OptionDefence' => 1,
      'Defence' => 160,
      'OptionCritical' => 1,
      'Critical' => 53,
      'OptionVitality' => 1,
      'Vitality' => 480,
      'Rate' => 5,
      'Star' => 3,
    ),
    8 => 
    array (
      'Name' => 'Huy Hieu Bien Ca',
      'OptionDamage' => 1,
      'Damage' => 170,
      'OptionDefence' => 1,
      'Defence' => 170,
      'OptionCritical' => 1,
      'Critical' => 56,
      'OptionVitality' => 1,
      'Vitality' => 510,
      'Rate' => 5,
      'Star' => 4,
    ),
    9 => 
    array (
      'Name' => 'Huy Hieu Song Ngu',
      'OptionDamage' => 1,
      'Damage' => 180,
      'OptionDefence' => 1,
      'Defence' => 180,
      'OptionCritical' => 1,
      'Critical' => 60,
      'OptionVitality' => 1,
      'Vitality' => 540,
      'Rate' => 5,
      'Star' => 4,
    ),
    10 => 
    array (
      'Name' => 'Huy Hieu Than Ngu',
      'OptionDamage' => 1,
      'Damage' => 190,
      'OptionDefence' => 1,
      'Defence' => 190,
      'OptionCritical' => 1,
      'Critical' => 63,
      'OptionVitality' => 1,
      'Vitality' => 570,
      'Rate' => 5,
      'Star' => 5,
    ),
  ),
  'QYellow' => 
  array (
    1 => 
    array (
      'Name' => 'Huy Hieu Dung Cam',
      'OptionDamage' => 1,
      'Damage' => 380,
      'OptionDefence' => 1,
      'Defence' => 380,
      'OptionCritical' => 1,
      'Critical' => 126,
      'OptionVitality' => 1,
      'Vitality' => 1140,
      'Rate' => 15,
      'Star' => 1,
    ),
    2 => 
    array (
      'Name' => 'Huy Hieu Kien Cuong',
      'OptionDamage' => 1,
      'Damage' => 420,
      'OptionDefence' => 1,
      'Defence' => 420,
      'OptionCritical' => 1,
      'Critical' => 140,
      'OptionVitality' => 1,
      'Vitality' => 1260,
      'Rate' => 15,
      'Star' => 1,
    ),
    3 => 
    array (
      'Name' => 'Huy Hieu Suc Manh',
      'OptionDamage' => 1,
      'Damage' => 460,
      'OptionDefence' => 1,
      'Defence' => 460,
      'OptionCritical' => 1,
      'Critical' => 153,
      'OptionVitality' => 1,
      'Vitality' => 1380,
      'Rate' => 15,
      'Star' => 1,
    ),
    4 => 
    array (
      'Name' => 'Huy Hieu Khong Tuoc',
      'OptionDamage' => 1,
      'Damage' => 500,
      'OptionDefence' => 1,
      'Defence' => 500,
      'OptionCritical' => 1,
      'Critical' => 166,
      'OptionVitality' => 1,
      'Vitality' => 1500,
      'Rate' => 15,
      'Star' => 2,
    ),
    5 => 
    array (
      'Name' => 'Huy Hieu Chien Tranh',
      'OptionDamage' => 1,
      'Damage' => 540,
      'OptionDefence' => 1,
      'Defence' => 540,
      'OptionCritical' => 1,
      'Critical' => 180,
      'OptionVitality' => 1,
      'Vitality' => 1620,
      'Rate' => 15,
      'Star' => 2,
    ),
    6 => 
    array (
      'Name' => 'Huy Hieu Bao Ve',
      'OptionDamage' => 1,
      'Damage' => 580,
      'OptionDefence' => 1,
      'Defence' => 580,
      'OptionCritical' => 1,
      'Critical' => 193,
      'OptionVitality' => 1,
      'Vitality' => 1740,
      'Rate' => 5,
      'Star' => 3,
    ),
    7 => 
    array (
      'Name' => 'Huy Hieu Than Linh',
      'OptionDamage' => 1,
      'Damage' => 620,
      'OptionDefence' => 1,
      'Defence' => 620,
      'OptionCritical' => 1,
      'Critical' => 206,
      'OptionVitality' => 1,
      'Vitality' => 1860,
      'Rate' => 5,
      'Star' => 3,
    ),
    8 => 
    array (
      'Name' => 'Huy Hieu Bien Ca',
      'OptionDamage' => 1,
      'Damage' => 660,
      'OptionDefence' => 1,
      'Defence' => 660,
      'OptionCritical' => 1,
      'Critical' => 220,
      'OptionVitality' => 1,
      'Vitality' => 1980,
      'Rate' => 5,
      'Star' => 4,
    ),
    9 => 
    array (
      'Name' => 'Huy Hieu Song Ngu',
      'OptionDamage' => 1,
      'Damage' => 700,
      'OptionDefence' => 1,
      'Defence' => 700,
      'OptionCritical' => 1,
      'Critical' => 233,
      'OptionVitality' => 1,
      'Vitality' => 2100,
      'Rate' => 5,
      'Star' => 4,
    ),
    10 => 
    array (
      'Name' => 'Huy Hieu Than Ngu',
      'OptionDamage' => 1,
      'Damage' => 740,
      'OptionDefence' => 1,
      'Defence' => 740,
      'OptionCritical' => 1,
      'Critical' => 246,
      'OptionVitality' => 1,
      'Vitality' => 2220,
      'Rate' => 5,
      'Star' => 5,
    ),
  ),
  'QPurple' => 
  array (
    1 => 
    array (
      'Name' => 'Huy Hieu Dung Cam',
      'OptionDamage' => 1,
      'Damage' => 1400,
      'OptionDefence' => 1,
      'Defence' => 1400,
      'OptionCritical' => 1,
      'Critical' => 466,
      'OptionVitality' => 1,
      'Vitality' => 4200,
      'Rate' => 22,
      'Star' => 1,
    ),
    2 => 
    array (
      'Name' => 'Huy Hieu Kien Cuong',
      'OptionDamage' => 1,
      'Damage' => 1500,
      'OptionDefence' => 1,
      'Defence' => 1500,
      'OptionCritical' => 1,
      'Critical' => 500,
      'OptionVitality' => 1,
      'Vitality' => 4500,
      'Rate' => 16,
      'Star' => 1,
    ),
    3 => 
    array (
      'Name' => 'Huy Hieu Suc Manh',
      'OptionDamage' => 1,
      'Damage' => 1600,
      'OptionDefence' => 1,
      'Defence' => 1600,
      'OptionCritical' => 1,
      'Critical' => 533,
      'OptionVitality' => 1,
      'Vitality' => 4800,
      'Rate' => 14,
      'Star' => 1,
    ),
    4 => 
    array (
      'Name' => 'Huy Hieu Khong Tuoc',
      'OptionDamage' => 1,
      'Damage' => 1700,
      'OptionDefence' => 1,
      'Defence' => 1700,
      'OptionCritical' => 1,
      'Critical' => 566,
      'OptionVitality' => 1,
      'Vitality' => 5100,
      'Rate' => 12,
      'Star' => 2,
    ),
    5 => 
    array (
      'Name' => 'Huy Hieu Chien Tranh',
      'OptionDamage' => 1,
      'Damage' => 1800,
      'OptionDefence' => 1,
      'Defence' => 1800,
      'OptionCritical' => 1,
      'Critical' => 600,
      'OptionVitality' => 1,
      'Vitality' => 5400,
      'Rate' => 11,
      'Star' => 2,
    ),
    6 => 
    array (
      'Name' => 'Huy Hieu Bao Ve',
      'OptionDamage' => 1,
      'Damage' => 1900,
      'OptionDefence' => 1,
      'Defence' => 1900,
      'OptionCritical' => 1,
      'Critical' => 633,
      'OptionVitality' => 1,
      'Vitality' => 5700,
      'Rate' => 9,
      'Star' => 3,
    ),
    7 => 
    array (
      'Name' => 'Huy Hieu Than Linh',
      'OptionDamage' => 1,
      'Damage' => 2000,
      'OptionDefence' => 1,
      'Defence' => 2000,
      'OptionCritical' => 1,
      'Critical' => 666,
      'OptionVitality' => 1,
      'Vitality' => 6000,
      'Rate' => 7,
      'Star' => 3,
    ),
    8 => 
    array (
      'Name' => 'Huy Hieu Bien Ca',
      'OptionDamage' => 1,
      'Damage' => 2200,
      'OptionDefence' => 1,
      'Defence' => 2200,
      'OptionCritical' => 1,
      'Critical' => 733,
      'OptionVitality' => 1,
      'Vitality' => 6600,
      'Rate' => 5,
      'Star' => 4,
    ),
    9 => 
    array (
      'Name' => 'Huy Hieu Song Ngu',
      'OptionDamage' => 1,
      'Damage' => 2500,
      'OptionDefence' => 1,
      'Defence' => 2500,
      'OptionCritical' => 1,
      'Critical' => 833,
      'OptionVitality' => 1,
      'Vitality' => 7500,
      'Rate' => 3,
      'Star' => 4,
    ),
    10 => 
    array (
      'Name' => 'Huy Hieu Than Ngu',
      'OptionDamage' => 1,
      'Damage' => 3000,
      'OptionDefence' => 1,
      'Defence' => 3000,
      'OptionCritical' => 1,
      'Critical' => 1000,
      'OptionVitality' => 1,
      'Vitality' => 9000,
      'Rate' => 1,
      'Star' => 5,
    ),
    11 => 
    array (
      'Name' => 'Huy Hieu Quy Ty',
      'OptionDamage' => 1,
      'Damage' => 4000,
      'OptionDefence' => 1,
      'Defence' => 4000,
      'OptionCritical' => 1,
      'Critical' => 1333,
      'OptionVitality' => 1,
      'Vitality' => 12000,
      'Rate' => 0,
      'Star' => 6,
    ),
    12 => 
    array (
      'Name' => 'Huy Hieu Hai Tac',
      'OptionDamage' => 1,
      'Damage' => 4000,
      'OptionDefence' => 1,
      'Defence' => 4000,
      'OptionCritical' => 1,
      'Critical' => 1333,
      'OptionVitality' => 1,
      'Vitality' => 12000,
      'Rate' => 0,
      'Star' => 6,
    ),
    13 => 
    array (
      'Name' => 'Huy Hieu Hai Ma',
      'OptionDamage' => 1,
      'Damage' => 4500,
      'OptionDefence' => 1,
      'Defence' => 4500,
      'OptionCritical' => 1,
      'Critical' => 1500,
      'OptionVitality' => 1,
      'Vitality' => 13500,
      'Rate' => 0,
      'Star' => 6,
    ),
  ),
  'QVIP' => 
  array (
    10 => 
    array (
      'Name' => 'Huy Hieu Than Ngu',
      'OptionDamage' => 1,
      'Damage' => 8000,
      'OptionDefence' => 1,
      'Defence' => 8000,
      'OptionCritical' => 1,
      'Critical' => 2666,
      'OptionVitality' => 1,
      'Vitality' => 24000,
      'Rate' => 0,
      'Star' => 5,
    ),
    13 => 
    array (
      'Name' => 'Huy Hieu Than Ngu',
      'OptionDamage' => 1,
      'Damage' => 12000,
      'OptionDefence' => 1,
      'Defence' => 12000,
      'OptionCritical' => 1,
      'Critical' => 4000,
      'OptionVitality' => 1,
      'Vitality' => 36000,
      'Rate' => 100,
      'Star' => 6,
    ),
  ),
);